// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AMenu: typeof import('@arco-design/web-vue')['Menu']
    AMenuItem: typeof import('@arco-design/web-vue')['MenuItem']
    ASubMenu: typeof import('@arco-design/web-vue')['SubMenu']
    Counter: typeof import('./src/components/Counter.vue')['default']
    DocSideBar: typeof import('./src/components/docs/DocSideBar.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Plum: typeof import('./src/components/Plum.vue')['default']
    README: typeof import('./src/components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TNav: typeof import('./src/components/TNav.vue')['default']
  }
}

export {}
